package com.example.pokocorp.animelistapp.activities.Fragments;


import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.example.pokocorp.animelistapp.R;
import com.example.pokocorp.animelistapp.activities.Adapters.RecyclerViewAdapterGrid;
import com.example.pokocorp.animelistapp.activities.Models.Anime;

import java.util.ArrayList;
import java.util.List;

import butterknife.BindView;
import butterknife.ButterKnife;

/**
 * A simple {@link Fragment} subclass.
 */
public class Home extends Fragment {

    private GridLayoutManager gLayout;
    @BindView(R.id.RV_anime_home)
    RecyclerView animeHome;
    private ArrayList<Anime> animes;

    public Home() {
        // Required empty public constructor
    }


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_home, container, false);
        ButterKnife.bind(this, view);

        initializeData();

        gLayout = new GridLayoutManager(this.getContext(), 4);

        animeHome.setHasFixedSize(true);
        animeHome.setLayoutManager(gLayout);

        RecyclerViewAdapterGrid rcAdapter = new RecyclerViewAdapterGrid(getContext(), animes);
        animeHome.setAdapter(rcAdapter);

        return view;
    }

    private void initializeData() {

        animes = new ArrayList<>();
        animes.add(new Anime(R.drawable.ansatsu, "Ansatsu Kyoushitsu","Ansatsu Kyoushitsu", "TV", "Action, Comedy, School, Shounen", "When a mysterious creature chops the moon down to a permanent crescent, the students of class 3-E of Kunugigaoka Middle School find themselves confronted with an enormous task: assassinate the creature responsible for the disaster before Earth suffers a similar fate. However, the monster, dubbed Koro-sensei (the indestructible teacher), is able to fly at speeds of up to Mach 20, which he demonstrates freely, leaving any attempt to subdue him in his extraterrestrial dust. Furthermore, the misfits of 3-E soon find that the strange, tentacled beast is more than just indomitable—he is the best teacher they have ever had!", 22, 8, false, false, 0));
        animes.add(new Anime(R.drawable.clockwork, "Clockwork Planet", "Clockwork Planet", "TV", "Sci-Fi, Fantasy", "One day, a black box suddenly crashed into the house of the high school dropout Naoto Miura. Inside it was a female automaton. The endless cycle of failure and success.\n" + "\n" + "The world that does change and the mankind that does not change. At a time where reality and fantasy are screaming, the encounters of these two make the gears of fate move!", 12, 6, false, false, 0));
        animes.add(new Anime(R.drawable.codegeass2, "Code Geass: R2", "Code Geass: Lelouch of the Rebellion R2", "TV", "Action, Military, Sci-Fi, Super Power, Drama, Mecha", "One year has passed since the Black Rebellion, a failed uprising against the Holy Britannian Empire led by the masked vigilante Zero, who is now missing. At a loss without their revolutionary leader, Area 11's resistance group—the Black Knights—find themselves too powerless to combat the brutality inflicted upon the Elevens by Britannia, which has increased significantly in order to crush any hope of a future revolt. \n" + "\n" + "Lelouch Lamperouge, having lost all memory of his double life, is living peacefully alongside his friends as a high school student at Ashford Academy. His former partner C.C., unable to accept this turn of events, takes it upon herself to remind him of his past purpose, hoping that the mastermind Zero will rise once again to finish what he started, in this thrilling conclusion to the series.", 25, 9, false, false, 0));
        animes.add(new Anime(R.drawable.dbs, "Dragon Ball Super", "Dragon Ball Super", "TV", "Action, Adventure, Comedy, Super Power, Martial Arts, Fantasy, Shounen", "Set just after the events of the Buu Saga of Dragon Ball Z, a deadly threat awakens once more. People lived in peace without knowing who the true heroes were during the devastating battle against Majin Buu. The powerful Dragon Balls have prevented any permanent damage, and our heroes also continue to live a normal life. In the far reaches of the universe, however, a powerful being awakens early from his slumber, curious about a prophecy of his defeat.\n" + "\n" + "Join Gokuu, Piccolo, Vegeta, Gohan, and the rest of the Dragon Ball crew as they tackle the strongest opponent they have ever faced. Beerus, the god of destruction, now sets his curious sights on Earth. Will the heroes save the day and prevent earth's destruction? Or will the whims of a bored god prove too powerful for the Saiyans? Gokuu faces impossible odds once more and fights for the safety of his loved ones and the planet.", 93, 7, false, false, 0));
        animes.add(new Anime(R.drawable.dungeonnideia, "Danmachi Oratoria", "Danmachi Sword Oratoria", "TV", "Action, Adventure, Fantasy", "Sword princess Aiz Wallenstein. Today, once again, the strongest female swordsman heads to the giant labyrinth known as the \"Dungeon\" along with her allies. On the 50th floor where mysteries and threats such as a decayed dragon's corpse that crumbles to ash and an irregularity that creeps ever closer to the party loom, Aiz calls for the wind and heads deeper into the darkness of the Dungeon. Eventually, she finds herself meeting a boy for the first time. \"Um, are you OK?\" In the Labyrinth City of Orario, the contrasting stories of the boy and the girl intersect!", 12, 7, false, false, 0));
        animes.add(new Anime(R.drawable.eromanga_sensei, "Eromanga-Sensei", "Eromanga-Sensei", "TV", "Comedy, Drama, Romance", "The \"new sibling romantic comedy\" revolves around Masamune Izumi, a light novel author in high school. Masamune's little sister is Sagiri, a shut-in girl who hasn't left her room for an entire year. She even forces her brother to make and bring her meals when she stomps the floor. Masamune wants his sister to leave her room, because the two of them are each other's only family.\n" + "\n" +"Masamune's novel illustrator, pen name \"Eromanga,\" draws extremely perverted drawings, and is very reliable. Masamune had never met his illustrator, and figured he was just a disgusting, perverted otaku. However, the truth is revealed... that his \"Eromanga-sensei\" is his own younger sister! To add to the chaos that erupts between the siblings, a beautiful, female, best-selling shoujo manga creator becomes their rival!", 12, 7, false, false, 0));
        animes.add(new Anime(R.drawable.fukumenkeinoise, "Fuumenkei Noise", "Fuumenkei Noise", "TV", "Music, Romance, Shoujo", "Every day, a young girl wearing a mask stands by the beach and sings a nostalgic melody. After experiencing two sudden heart-wrenching partings when she was only a child, Nino Arisugawa has been singing her songs to the ocean, bound by a promise made with her two childhood friends—her first love, Momo Sakaki, and a boy who composed music, Kanade \"Yuzu\" Yuzuhira. Having never met each other, the boys both individually promised that if Nino was ever separated from them, her voice would be the beacon to reunite them once again.\n" + "\n" +"After six long years, destiny has finally placed Nino, Momo, and Yuzu in the same high school. However, the passage of time has changed many things in their lives—while Nino relentlessly attempts to fulfill her childhood promise with the boys, Yuzu's feelings for her from the past resurface, and Momo goes to great lengths to prevent a reunion with Nino. Through music, will they be able to mend their friendship and overcome all the feelings involved in this complicated love triangle?", 12, 6, false, false, 0));
        animes.add(new Anime(R.drawable.granblue, "GRANBLUE FANTASY", "GRANBLUE FANTASY the animation", "TV", "Fantasy", "This is a world of the skies, where many islands drift in the sky. A boy named Gran and a talking winged lizard named Vyrn lived in Zinkenstill, an island which yields mysteries. One day, they come across a girl named Lyria. Lyria had escaped from the Erste Empire, a military government that is trying to rule over this world using powerful military prowess. In order to escape from the Empire, Gran and Lyria head out into the vast skies, holding the letter Gran's father left behind—which said, \"I will be waiting at Estalucia, Island of Stars.\"", 14, 7, false, false, 0));
        animes.add(new Anime(R.drawable.haikyuu3, "Haikyu!! 3", "Haikyu!! 3rd Season", "TV", "Comedy, Sports, Drama, School, Shounen", "The third season of Haikyuu!!", 10, 9, false, false, 0));
        animes.add(new Anime(R.drawable.hainne, "Kyoushi Haine", "Oushitsu Kyoushi Haine", "TV", "Comedy", "Accepting the post of Royal Tutor at the court of the king of Grannzreich, Heine Wittgenstein is a little professor with a big job ahead! Each of the kingdom's four princes has a rather distinct personality. Does their diminutive new instructor have what it takes to lay down some learning? It's a comedy of educational proportions!", 9, 7, false, false, 0));
        animes.add(new Anime(R.drawable.nanatsunotaizai, "Nanatsu no Taizai", "Nanatsu no Taizai", "TV", "Action, Adventure, Supernatural, Ecchi, Fantasy, Shounen", "In a world similar to the European Middle Ages, the feared yet revered Holy Knights of Britannia use immensely powerful magic to protect the region of Britannia and its kingdoms. However, a small subset of the Knights supposedly betrayed their homeland and turned their blades against their comrades in an attempt to overthrow the ruler of Liones. They were defeated by the Holy Knights, but rumors continued to persist that these legendary knights, called the \"Seven Deadly Sins,\" were still alive. Ten years later, the Holy Knights themselves staged a coup d’état, and thus became the new, tyrannical rulers of the Kingdom of Liones.\n" + "\n" +"Based on the best-selling manga series of the same name, Nanatsu no Taizai follows the adventures of Elizabeth, the third princess of the Kingdom of Liones, and her search for the Seven Deadly Sins. With their help, she endeavors to not only take back her kingdom from the Holy Knights, but to also seek justice in an unjust world.", 24, 8, false, false, 0));
        animes.add(new Anime(R.drawable.recreators, "Re:creators", "Re:CREATORS", "TV", "Action, Sci-Fi, Fantasy, Seinen", "Humans have designed countless worlds—each one born from the unique imagination of its creator. Souta Mizushino is a high school student who aspires to be such a creator by writing and illustrating his own light novel. One day, while watching anime for inspiration, he is briefly transported into a fierce fight scene. When he returns to the real world, he realizes something is amiss: the anime's headstrong heroine, Celestia Yupitilia, has somehow returned with him.\n" + "\n" + "Before long, other fictional characters appear in the world, carrying the hopes and scars of their home. A princely knight, a magical girl, a ruthless brawler, and many others now crowd the streets of Japan. However, the most mysterious one is a woman in full military regalia, dubbed \"Gunpuku no Himegimi,\" who knows far more than she should about the creators' world. Despite this, no one knows her true name or the world she is from.\n" + "\n" + "Meanwhile, Souta and Celestia work together with Meteora Österreich, a calm and composed librarian NPC, to uncover the meaning behind these unnatural events. With powerful forces at play, the once clear line between reality and imagination continues to blur, leading to a fateful meeting between creators and those they created.", 22, 7, false, false, 0));
        animes.add(new Anime(R.drawable.renai, "Renai Boukun", "Renai Boukun", "TV", "Comedy, Supernatural, Romance, School", "A Kiss Note is a powerful notebook that makes anyone who has their name written together will instantly fall in love if they kiss each other regardless of any circumstances. This magical and very familiar item belongs to an angel named Guri whose job as cupid is to create couples. However, she accidentally writes down Aino Seiji, a regular high school student, and unless he kisses someone, Guri will die. She convinces Seiji to go kiss his crush, Hiyama Akane, the school's popular girl who turns out has even stronger feelings for him, bordering on obsessive and psychotic. Eventually Akane and Seiji come together but not before Guri decides that she likes Seiji as well. What seems awesome to most guys becomes hell for Seiji who just wants a normal relationship with girls.", 12, 7, false, false, 0));
        animes.add(new Anime(R.drawable.rokudenashi, "Akashic Records", "Akashic Records of Bastard Magic Instructor", "TV", "Action, Magic, Fantasy, School", "Sistine attends a magical academy to hone her skills in the magical arts, hoping to solve the mystery of the enigmatic Sky Castle. After the retirement of her favorite teacher, the replacement, Glenn, turns out to be a tardy, lazy, and seemingly incompetent bastard of an instructor. How is it that Glenn was hand-picked by the best magician in the academy?!", 12, 7, false, false, 0));
        animes.add(new Anime(R.drawable.shingeki2, "Shingeki no Kyojin 2", "Shingeki no Kyojin Season 2", "TV", "Action, Adventure, Fantasy", "Second season of Shingeki no Kyojin.", 12, 8, false, false, 0));
        animes.add(new Anime(R.drawable.shuumatsu, "WorldEnd", "WorldEnd: What do you do at the end of the world? Are you busy? Will you save us?", "TV", "Sci-Fi, Drama, Romance, Fantasy", "Five hundred years have passed since the humans went extinct at the hands of the fearsome and mysterious 'Beasts.' The surviving races now make their homes up on floating islands in the sky, out of reach of all but the most mobile of Beasts.\n" + "\n" + "Only a small group of young girls, the Leprechauns, can wield the ancient weapons needed to fend off invasions from these creatures. Into the girls' unstable and fleeting lives, where a call to certain death could come at any moment, enters an unlikely character: a young man who lost everything in his final battle five hundred years ago, the last living human awakened from a long, icy slumber.\n" + "\n" + "Unable to fight any longer, Willem becomes the father that the girls never had, caring for and nurturing them even as he struggles to come to terms with his new life, in which he feels the pain of helplessly waiting for his loved ones to return home from battle that his 'Daughter' once felt for him so long ago. Together, Willem and the girls gradually come to understand what family means and what is truly worth protecting.", 6, 7, false, false, 0));
        animes.add(new Anime(R.drawable.sinnanatsu, "Sin: Nanatsu no Taizai", "Sin: Nanatsu no Taizai", "TV", "Ecchi, Fantasy", "You, will you be a worshipper of the devil lords? These beautiful lords lead humans to the seven deadly sins: pride, envy, wrath, sloth, greed, gluttony, and lust. A revealing fantasy that craves to corrupt and steal true happiness starts now.", 12, 5, false, false, 0));
        animes.add(new Anime(R.drawable.souryo, "Souryo to Majiwaru", "Souryo to Majiwaru Shikiyoku no Yoru ni", "TV", "Drama, Romance, Josei", "At a high school reunion, Mio Fukatani reunites with a classmate she has not seen in years—Takahide Kujou. She had always wanted to know more about the kind-hearted boy in high school, but once she realizes that Kujou has become a monk, she believes that any chance of getting to know him romantically is slim. Deciding to drink away her sorrows, she ends up walking home drunk, and surprisingly, running into Kujou who helps her get home.\n" + "\n" + "However, once inside, Kujou's lust for Mio becomes apparent and the two share an erotic night of passion. As this steamy romance blossoms between these two unlikely lovers, Mio and Kujou will undoubtedly spend many nights together in utter ecstasy.", 12, 4, false, false, 0));
        animes.add(new Anime(R.drawable.tsukigakirei, "Tsukigakirei", "Tsuki ga kirei", "TV", "Romance, School", "Kotarou Azumi and Akane Mizuno became third year students at junior high school and are classmates for the first time. These two, along with fellow classmates, Chinatsu Nishio and Takumi Hira, relate to their peers through mutual understandings and feelings. As their final year at junior high school progresses, the group overcome their challenges to mature and become aware of changes in themselves.", 7, 7, false, false, 0));


    }

}
